_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: es
uuid: 6ba9bxxx-xxxx-438x-9c8x-e5x7x3d0x347
name: 'Joker System'
mail: keevj1999@gmail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: es
